version: '3.8'

services:
  nginx:
    image: nginx:1.21.6
    container_name: Nginx
    ports:
      - "4001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html
    networks:
      - front
      - back

  php:
    image: php:8.0-fpm
    container_name: PHP
    volumes:
      - ./html:/var/www/html
    networks:
      - back

  mysql:
    image: mysql:8.0.37
    container_name: MySQL
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - back

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: phpMyAdmin
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    ports:
      - "6001:80"
    networks:
      - back

volumes:
  mysql_data:

networks:
  front:
  back:
